### ISSUE TITLE
Typing line number before gg or G doesn't take you to that line

### ISSUE THREAD

**Issue by cybardev** [nparkanyi/gedit3-vim-mode#8]
In regular vim, using `17gg` or `17G` in Normal mode would take me to the 17th line. Trying that in Gedit with this plugin just ignores the number and takes me to the start (`gg`) or end (`G`) of the file.

Could you please add that functionality?

Currently, doing `5e` does take me to the end of the 5th word, and w, b, etc. works just fine too. So I assume the code will be similar to that.

Thanks for the wonderful plugin though. Makes Gedit a much better editor.

**Comment by JonLiuFYI** [comment]
@cybarspace Remember this issue? I've implemented this feature, so please give my fork a try. I think I've squished all the edge cases.

**Comment by cybardev** [comment]
> @cybarspace Remember this issue? I've implemented this feature, so please give my fork a try. I think I've squished all the edge cases.

Thanks for letting me know 😀
I'll be sure to try it out. Cheers 🎉

Edit: That worked *perfectly*. Thanks a lot. :D
